apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    run.googleapis.com/build-enable-automatic-updates: 'false'
    run.googleapis.com/build-id: 719f531b-7c77-4de9-a5ef-6ad8f8a95ddc
    run.googleapis.com/build-image-uri: us-central1-docker.pkg.dev/crested-unity-391222/cloud-run-source-deploy/ws-relay-server
    run.googleapis.com/build-name: projects/711566525822/locations/global/builds/719f531b-7c77-4de9-a5ef-6ad8f8a95ddc
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
    run.googleapis.com/urls: '["https://ws-relay-server-711566525822.us-central1.run.app","https://ws-relay-server-wc4kh766gq-uc.a.run.app"]'
  labels:
    cloud.googleapis.com/location: us-central1
  name: ws-relay-server
  namespace: '711566525822'
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '100'
        run.googleapis.com/client-name: gcloud
        run.googleapis.com/client-version: 527.0.0
        run.googleapis.com/startup-cpu-boost: 'true'
      labels:
        client.knative.dev/nonce: sedmuhhluf
        run.googleapis.com/startupProbeType: Default
    spec:
      containerConcurrency: 80
      containers:
      - image: us-central1-docker.pkg.dev/crested-unity-391222/cloud-run-source-deploy/ws-relay-server
        ports:
        - containerPort: 8080
          name: h2c
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
        startupProbe:
          failureThreshold: 1
          periodSeconds: 240
          tcpSocket:
            port: 8080
          timeoutSeconds: 240
      serviceAccountName: 711566525822-compute@developer.gserviceaccount.com
      timeoutSeconds: 300
  traffic:
  - latestRevision: true
    percent: 100
